package banque;
/**
* CompteCourantPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* jeudi 26 septembre 2024 16 h 35 CEST
*/

public class CompteCourantPOATie extends CompteCourantPOA
{

  // Constructors

  public CompteCourantPOATie ( CompteCourantOperations delegate ) {
      this._impl = delegate;
  }
  public CompteCourantPOATie ( CompteCourantOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public CompteCourantOperations _delegate() {
      return this._impl;
  }
  public void _delegate (CompteCourantOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean DecouvertAutorise ()
  {
    return _impl.DecouvertAutorise();
  } // DecouvertAutorise
  public void DecouvertAutorise (boolean newDecouvertAutorise)
  {
    _impl.DecouvertAutorise(newDecouvertAutorise);
  } // DecouvertAutorise

  public float lire_montant ()
  {
    return _impl.lire_montant();
  } // lire_montant

  public void crediter (float somme_credit)
  {
    _impl.crediter(somme_credit);
  } // crediter

  public void debiter (float somme_debit)
  {
    _impl.debiter(somme_debit);
  } // debiter

  private CompteCourantOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class CompteCourantPOATie
