package banque;
/**
* CompteCourantRemunere.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* jeudi 26 septembre 2024 16 h 35 CEST
*/

public interface CompteCourantRemunere extends CompteCourantRemunereOperations, CompteCourant, CompteEpargne
{
} // interface CompteCourantRemunere
