package banque;
/**
* CompteEpargneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* jeudi 26 septembre 2024 16 h 35 CEST
*/

public interface CompteEpargneOperations  extends CompteBOperations
{
  int taux ();
  void taux (int newTaux);
} // interface CompteEpargneOperations
