package banque;
/**
* CompteBOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* jeudi 26 septembre 2024 16 h 35 CEST
*/

public interface CompteBOperations 
{
  float lire_montant ();
  void crediter (float somme_credit);
  void debiter (float somme_debit);
} // interface CompteBOperations
