package banque;
/**
* CompteBHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* jeudi 26 septembre 2024 16 h 35 CEST
*/

abstract public class CompteBHelper
{
  private static String  _id = "IDL:CompteB:1.0";

  public static void insert (org.omg.CORBA.Any a, CompteB that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CompteB extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CompteBHelper.id (), "CompteB");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CompteB read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CompteBStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CompteB value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CompteB narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CompteB)
      return (CompteB)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _CompteBStub stub = new _CompteBStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CompteB unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CompteB)
      return (CompteB)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _CompteBStub stub = new _CompteBStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
