package banque;
/**
* CompteBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* jeudi 26 septembre 2024 16 h 35 CEST
*/

public final class CompteBHolder implements org.omg.CORBA.portable.Streamable
{
  public CompteB value = null;

  public CompteBHolder ()
  {
  }

  public CompteBHolder (CompteB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompteBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompteBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompteBHelper.type ();
  }

}
