package banque;
/**
* CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* vendredi 20 septembre 2024 12 h 38 CEST
*/

public interface CompteOperations 
{
  void lireMontant ();
  void crediter (double montant);
  void debiter (double montant);
} // interface CompteOperations
