package banque;
/**
* Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* vendredi 20 septembre 2024 12 h 38 CEST
*/

public interface Compte extends CompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compte
