package hello;
/**
* Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* vendredi 20 septembre 2024 12 h 33 CEST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
